// automaticly generated by wsjcpp:v0.2.7

#include "__build_simple_sh_path66c8dc.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___build_simple_sh_path66c8dc)

const std::string &RES___build_simple_sh_path66c8dc::getFilename() const {
    static const std::string s = "./build_simple.sh";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___build_simple_sh_path66c8dc::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___build_simple_sh_path66c8dc::getBufferSize() const {
    return 592;
}

// ---------------------------------------------------------------------

const char *RES___build_simple_sh_path66c8dc::getBuffer() const {
    static const std::string sRet = "" // size: 592
        "#!/bin/bash\n"
        "\n"
        "check_ret() {\n"
        "    if [ $1 -ne 0 ]; then\n"
        "        echo \"\"\n"
        "        echo \"!!! FAIL: $2\"\n"
        "        echo \"********************************************************************************\"\n"
        "        echo \"\"\n"
        "        exit $1\n"
        "    else\n"
        "        echo \"\"\n"
        "        echo \"*** SUCCESS: $2\"\n"
        "        echo \"********************************************************************************\"\n"
        "        echo \"\"\n"
        "    fi\n"
        "}\n"
        "\n"
        "# if [ ! -d tmp ]; then\n"
        "#     mkdir -p tmp\n"
        "# fi\n"
        "\n"
        "cmake -H. -Btmp/release -DCMAKE_BUILD_TYPE=Release\n"
        "check_ret $? \"configure\"\n"
        "\n"
        "cmake --build tmp/release --config Release\n"
        "check_ret $? \"make\"\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


