// automaticly generated by wsjcpp:v0.2.2

#include "__build_simple_sh_pathd79e07.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___build_simple_sh_pathd79e07)

const std::string &RES___build_simple_sh_pathd79e07::getFilename() const {
    static const std::string s = "./build_simple.sh";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___build_simple_sh_pathd79e07::getPackAs() const {
    static const std::string s = "text";
    return s;
}
// ---------------------------------------------------------------------

int RES___build_simple_sh_pathd79e07::getBufferSize() const {
    return 513;
}

// ---------------------------------------------------------------------

const char *RES___build_simple_sh_pathd79e07::getBuffer() const {
    static const std::string sRet = "" // size: 513
        "#!/bin/bash\n"
        "\n"
        "check_ret() {\n"
        "    if [ $1 -ne 0 ]; then\n"
        "        echo \"\"\n"
        "        echo \"!!! FAIL: $2\"\n"
        "        echo \"********************************************************************************\"\n"
        "        echo \"\"\n"
        "        exit $1\n"
        "    else\n"
        "        echo \"\"\n"
        "        echo \"*** SUCCESS: $2\"\n"
        "        echo \"********************************************************************************\"\n"
        "        echo \"\"\n"
        "    fi\n"
        "}\n"
        "\n"
        "if [ ! -d tmp ]; then\n"
        "    mkdir -p tmp\n"
        "fi\n"
        "\n"
        "cd tmp\n"
        "cmake ..\n"
        "check_ret $? \"configure\"\n"
        "\n"
        "make\n"
        "check_ret $? \"make\"\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


