// automaticly generated by wsjcpp:v0.1.7

#include <wsjcpp_resources_manager.h>

class RES___build_simple_sh_pathd79e07 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


