// automaticly generated by wsjcpp:v0.2.7

#include <wsjcpp_core.h>

class RES___build_simple_sh_path66c8dc : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


