// automaticly generated by wsjcpp:v0.1.2

#include <wsjcpp_resources_manager.h>

class RES_build_simple_sh_path311e3d : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename();
        virtual const int getBufferSize();
        virtual const char *getBuffer();
};


