// automaticly generated by wsjcpp:v0.1.2

#include <wsjcpp_resources_manager.h>

class RES_build_simple_sh_path311e3d : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const;
        virtual const std::string &getPackAs() const;
        virtual int getBufferSize() const;
        virtual const char *getBuffer() const;
};


