// automaticly generated by wsjcpp:v0.1.2

#include <build_simple_sh_path311e3d.h>

REGISTRY_WSJCPP_RESOURCE_FILE(RES_build_simple_sh_path311e3d)

const std::string &RES_build_simple_sh_path311e3d::getFilename() {
    static const std::string s = "build_simple.sh";
    return s;
}

// ---------------------------------------------------------------------

const int RES_build_simple_sh_path311e3d::getBufferSize() {
    return 74;
}

// ---------------------------------------------------------------------

const char *RES_build_simple_sh_path311e3d::getBuffer() {
    static const std::string sRet = "" // size: 74
        "#!/bin/bash\n"
        "\n"
        "if [ ! -d tmp ]; then\n"
        "	mkdir -p tmp\n"
        "fi\n"
        "\n"
        "cd tmp\n"
        "cmake ..\n"
        "make\n"
        ""
    ;
    return sRet.c_str();
} //::buffer() 


